// <auto-generated />
using System;
using Case.DatabaseContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Case.Migrations
{
    [DbContext(typeof(Context))]
    partial class ContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Case.Entity.Demand", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("Complaint")
                        .IsRequired()
                        .HasColumnType("nvarchar(4000)")
                        .HasColumnName("complaint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(254)")
                        .HasColumnName("name");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(254)")
                        .HasColumnName("useer_name");

                    b.HasKey("Id");

                    b.ToTable("Demand");
                });
#pragma warning restore 612, 618
        }
    }
}
